// 所有服务商都走 OpenAI 兼容协议，接入任何一家只需要改三个东西：服务地址、API Key、模型名。
// imageModels：该服务商支持的绘图模型（文生图走 /images/generations 接口）；
// imageHint：绘图相关说明；绘图与聊天共用同一个服务地址和 Key。
export const PROVIDER_PRESETS = {
  demo: {
    label: '演示模式（无需 Key）',
    baseUrl: 'http://localhost:8788/v1',
    apiKey: 'demo',
    models: ['demo-model'],
    keyUrl: '',
    hint: '先在项目目录运行 node mock-server.mjs 启动演示服务，即可体验完整的流式对话效果。',
    imageModels: ['demo-image-model'],
    imageHint: '本地演示：返回程序画的占位图，文生图 / 图生图都能演示，无需联网。',
  },
  deepseek: {
    label: 'DeepSeek（深度求索）',
    baseUrl: 'https://api.deepseek.com',
    apiKey: '',
    models: ['deepseek-chat', 'deepseek-reasoner'],
    keyUrl: 'https://platform.deepseek.com/api_keys',
    hint: 'deepseek-reasoner（R1）会先输出「思考过程」；DeepSeek 暂不支持图片输入。',
    imageModels: [],
    imageHint: 'DeepSeek 暂无绘图能力，要画图请切换到魔搭、硅基流动或 xAI。',
  },
  xai: {
    label: 'Grok（xAI）',
    baseUrl: 'https://api.x.ai/v1',
    apiKey: '',
    models: ['grok-4', 'grok-4-fast', 'grok-3', 'grok-3-mini'],
    keyUrl: 'https://console.x.ai',
    hint: '模型名以 xAI 官方文档为准，可直接手动输入。',
    imageModels: ['grok-2-image-1212'],
    imageHint: 'Grok 图像接口只支持文生图，不支持图生图；模型名以官方文档为准。',
  },
  modelscope: {
    label: '魔搭社区 ModelScope',
    baseUrl: 'https://api-inference.modelscope.cn/v1',
    apiKey: '',
    models: [
      'Qwen/Qwen3-235B-A22B',
      'deepseek-ai/DeepSeek-V3',
      'deepseek-ai/DeepSeek-R1',
      'Qwen/Qwen2.5-VL-72B-Instruct',
    ],
    keyUrl: 'https://modelscope.cn/my/myaccesstoken',
    hint: '魔搭 API-Inference 有免费额度，需在官网实名并开通；Key 在「访问令牌」页面创建。发图片请选 VL 系列视觉模型。',
    imageModels: ['Qwen/Qwen-Image', 'Qwen/Qwen-Image-Edit', 'black-forest-labs/FLUX.1-schnell'],
    imageHint: 'Qwen-Image 负责文生图；图生图请选 Qwen-Image-Edit 并上传参考图；FLUX 仅文生图。绘图与对话共用同一个 Key。',
  },
  siliconflow: {
    label: '硅基流动 SiliconFlow',
    baseUrl: 'https://api.siliconflow.cn/v1',
    apiKey: '',
    models: ['deepseek-ai/DeepSeek-V3', 'Qwen/Qwen2.5-72B-Instruct', 'THUDM/GLM-4-9B-Chat'],
    keyUrl: 'https://cloud.siliconflow.cn/account/ak',
    hint: '国内直连、注册送额度，聚合 DeepSeek / Qwen / GLM 等模型，API Key 在官网「API 密钥」页创建。',
    imageModels: ['Qwen/Qwen-Image', 'black-forest-labs/FLUX.1-schnell', 'stabilityai/stable-diffusion-3-5-large', 'Qwen/Qwen-Image-Edit'],
    imageHint: '绘图与对话共用同一个 Key；图生图请选 Qwen-Image-Edit。',
  },
  xpivot: {
    label: 'XPivot 中转站',
    baseUrl: 'https://www.xpivot.top/v1',
    apiKey: '',
    models: ['grok-4.5'],
    keyUrl: 'https://www.xpivot.top/console/token',
    hint: '第三方中转聚合服务。登录官网后在「令牌」页创建 Key（sk- 开头）粘贴到这里；聊天与绘图的 Key 不同时，请在编辑里分别填写（绘图 Key 留空则沿用聊天 Key）。',
    imageModels: ['gpt-image-2.5-flare', 'gpt-image-2.5-sunburst'],
    imageHint: 'gpt-image 系列生图模型（flare / sunburst）。若生图 Key 与聊天 Key 不同，请到编辑里单独填写「绘图 Key」。',
  },
  apimart: {
    label: 'ApiMart 中转站',
    baseUrl: 'https://api.apimart.ai/v1',
    apiKey: '',
    models: [],
    keyUrl: 'https://apimart.ai/keys',
    hint: '聚合中转站。文本模型名到官网 apimart.ai/model 页查看后手动填入（如 claude / gemini / gpt 系列）；聊天与绘图的 Key 不同时分别填写。',
    imageModels: ['gpt-image-2.5-flare', 'gpt-image-2.5-sunburst'],
    imageHint: 'gpt-image-2.5 系列：flare 出图快，sunburst 擅长精确编辑。走异步任务自动轮询（约 1~3 分钟），图生图会先自动上传参考图（官方仅收 72 小时临时链接）。',
  },
  custom: {
    label: '自定义（任何 OpenAI 兼容服务）',
    baseUrl: '',
    apiKey: '',
    models: [],
    keyUrl: '',
    hint: '填入任意 OpenAI 兼容服务的地址、Key 和模型名即可，例如 agens-ai、中转站等。',
    imageModels: [],
    imageHint: '只要该服务支持 /images/generations 接口就能画图：填地址、Key 和绘图模型名。',
  },
}
